# Generated by Django 4.1.6 on 2023-04-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('company_currency', models.CharField(max_length=10)),
                ('company_country', models.CharField(max_length=50)),
                ('company_industry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('stock', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
