# Generated by Django 4.1.6 on 2023-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='company_industry',
            field=models.CharField(max_length=200),
        ),
    ]
