# Generated by Django 4.1.6 on 2023-03-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_stockdata_delete_stocks_stock_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
