# Generated by Django 4.1.6 on 2023-04-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_remove_stockpredictiondata_correct_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpredictionhistory',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
    ]
