version: "3.7"

services:
  stockpredictor-db:
    image: mysql:8.0
    container_name: stockpredictor-db
    volumes:
      - ./database/db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "stockpredictor"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"

  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=django-insecure-9@l^-qwhrrjusb1yqj5iu-qsfn635likb512k9(2b=(#i2%oe)
      - ALLOWED_HOSTS=stockpredictorapp.com,www.stockpredictorapp.com,77.68.115.53
    depends_on:
      - stockpredictor-db

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "80:80"
    depends_on:
      - app
  pma:
    restart: on-failure
    image: phpmyadmin/phpmyadmin
    container_name: stockpredictor-pma
    ports:
      - 4000:80
    environment:
      PMA_HOST: stockpredictor-db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M

volumes:
  static_data:
